name: e2e-kind
on:
  - pull_request

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: "Install GoLang"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: "Checkout Repo"
        uses: actions/checkout@v2
      - name: "Build CLI"
        run: make build-cli-windows
