name: e2e-windows
on:
  - pull_request

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: "Install GoLang"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: "Checkout Repo"
        uses: actions/checkout@v2
      - name: "Build CLI"
        run: make build-cli-windows
      - name: "Test zarf.exe works"
        run: |
          make zarf-bin
          make foo
      - name: "Create the init package"
        run: make init-package
